index:
    path: /
    controller: App\Controller\ApiController::index
login:
    path: /login
    controller: App\Controller\ApiController::login
register:
    path: /register
    controller: App\Controller\ApiController::register